language: node_js

node_js:
  - 6 # Active LTS until April 2019
  - 8 # Active LTS until December 2019
  - 9 # Current

os:
  - linux
  - osx

cache:
  directories:
    - node_modules
    - e2e/node_modules
  yarn: true

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

script:
  - yarn lint
  - yarn lib
#  - yarn test -- --coverage TODO: write a test suite
  # E2E
  - cd e2e
  - yarn --pure-lock
  - yarn benchmark

#after_success: yarn coveralls TODO: write a test suite
